# Generated by Django 5.1.3 on 2024-11-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'GPU'), ('Motherboard', 'Motherboard'), ('RAM', 'RAM'), ('Storage', 'Storage'), ('Power Supply', 'Power Supply'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
