# Generated by Django 5.1.3 on 2024-11-15 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_activitylog_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
