# Generated by Django 5.1.3 on 2025-11-14 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_view_reports', 'Can view inventory reports and activity logs'), ('can_manage_inventory', 'Can add, edit, and delete inventory items')]},
        ),
    ]
